import { PlotSettings } from "./types";

export const DEFAULT_PLOT_SETTINGS: PlotSettings = {
  title: "",
  titleStyle: { bold: true, italic: false, color: "#000000" },
  titleFontSize: 16,
  xLabel: "",
  xLabelStyle: { bold: true, italic: false, color: "#000000" },
  yLabel: "",
  yLabelStyle: { bold: true, italic: false, color: "#000000" },
  xAxisLabelFontSize: 12,
  yAxisLabelFontSize: 12,
  xTickLabelFontSize: 10,
  yTickLabelFontSize: 10,
  showLegend: true,
  hideSystemLegend: true,
  hideSystemLegendOnExport: true,
  legendFontSize: 12,
  showGridX: true,
  showGridY: true,
  gridLineWidthX: 1,
  gridLineWidthY: 1,
  axisLineWidthX: 1,
  axisLineWidthY: 1,
  aspectRatio: 16 / 9,
  legendPosition: { x: 100, y: 100 },
};
